/**
 * Generate and download an AHP analysis report as Markdown
 */

function generateMarkdownReport(criteria, results) {
    const { weights, ci, cr, lambdaMax } = results;
    const { THRESHOLD_GOOD, THRESHOLD_ACCEPTABLE } = window.preferences.CR;
    
    // Create ranking
    const ranking = criteria
        .map((name, idx) => ({ name, weight: weights[idx] }))
        .sort((a, b) => b.weight - a.weight);
    
    // Get representative criteria for the summary
    const c1 = ranking[0];
    const c2 = ranking[1];
    const c3 = ranking[ranking.length - 1];
    
    const timestamp = new Date().toLocaleDateString();
    
    // Section 1: Priority Ranking
    const priorityNarrative = `Across ${criteria.length * (criteria.length - 1) / 2} criterion pairs, ${c1.name} received the highest weight (${(c1.weight * 100).toFixed(1)}%), followed by ${c2.name} (${(c2.weight * 100).toFixed(1)}%). ${c3.name} received the lowest weight (${(c3.weight * 100).toFixed(1)}%). These weights reflect the comparisons you entered and sum to 100%.`;
    
    // Section 2: Consistency
    const consistencyNarrative = cr < THRESHOLD_GOOD 
        ? `The consistency ratio is below ${THRESHOLD_GOOD}. This indicates that the comparisons are reasonably consistent under the app's threshold; it does not validate the underlying judgment or guarantee a good decision.`
        : `The consistency ratio is above ${THRESHOLD_GOOD}. Review comparisons that may conflict with one another before relying on these weights.`;
    
    // Section 3: Technical Metrics table with formulas
    const technicalMetrics = `
| Metric | Value | Formula | Interpretation |
|--------|-------|---------|-----------------|
| Lambda Max (λ_max) | ${lambdaMax.toFixed(4)} | Eigenvalue of pairwise matrix | Measures how well the matrix satisfies the consistency condition. Closer to n (${criteria.length}) indicates perfect consistency; higher values suggest logical contradictions. |
| Consistency Index (CI) | ${ci.toFixed(4)} | (λ_max - n) / (n - 1) | Normalized measure of deviation from perfect consistency. Lower values indicate more coherent judgments. A CI of 0 means perfect consistency. |
| Consistency Ratio (CR) | ${cr.toFixed(4)} | CI / RI | CR < ${THRESHOLD_GOOD} meets the app's consistency threshold; higher values suggest review. |
| Criteria Count | ${criteria.length} | n | Total number of decision criteria. The matrix dimension; more criteria mean more comparisons and potential for inconsistency. |
`;

    const methodNarrative = `This analysis uses the Analytic Hierarchy Process (AHP) to convert pairwise judgments into relative criterion weights. Your ${criteria.length} × ${criteria.length} comparison matrix was processed using the power method. The consistency metrics measure how closely the judgments fit a consistent comparison matrix.`;

    const markdown = `# AHP Decision Analysis

**Generated:** ${timestamp} | **Criteria:** ${criteria.length} | **Consistency Ratio:** ${cr.toFixed(4)}

## What your comparisons revealed

${priorityNarrative}

| Rank | Criterion | Weight |
|------|-----------|--------|
${ranking.map((item, idx) => `| ${idx + 1} | ${item.name.replace(/\|/g, '\\|').replace(/\r?\n/g, ' ')} | ${(item.weight * 100).toFixed(2)}% |`).join('\n')}

## How reliable are these results

Consistency Ratio: ${cr.toFixed(4)}. ${cr < THRESHOLD_GOOD ? `Below ${THRESHOLD_GOOD} threshold — reasonably consistent.` : cr < THRESHOLD_ACCEPTABLE ? `Between ${THRESHOLD_GOOD} and ${THRESHOLD_ACCEPTABLE} — review comparisons.` : `Above ${THRESHOLD_ACCEPTABLE} — substantial inconsistency; revise comparisons.`}

${consistencyNarrative}

## Methodology reference

${technicalMetrics}

### How AHP works

${methodNarrative} Each pairwise comparison (e.g., "Does Cost matter more than Speed?") is captured on a 9-point scale, then synthesized mathematically to produce the priority weights above.

## A note on interpretation

AHP surfaces the internal logic of your own priorities — it does not make the decision for you. Use these weights as a structured input, not a final answer. Your judgment, context, and information beyond this analysis remain the deciding factors. If your CR exceeds the acceptable threshold, treat the results as directional guidance rather than precise rankings.

---

Generated by AHP Decision Dashboard, Noufal Rizka · ${timestamp}`;

    return markdown;
}

function downloadReport(criteria, results) {
    const markdown = generateMarkdownReport(criteria, results);
    
    // Create blob
    const blob = new Blob([markdown], { type: 'text/markdown' });
    
    // Create download link
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AHP-Report-${new Date().toISOString().split('T')[0]}.md`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
}

window.generateMarkdownReport = generateMarkdownReport;
window.downloadReport = downloadReport;
