/**
 * Generate and download AHP analysis report as markdown
 */

function generateMarkdownReport(criteria, results) {
    const { weights, ci, cr, lambdaMax } = results;
    const { THRESHOLD_GOOD, THRESHOLD_ACCEPTABLE } = window.preferences.CR;
    
    // Create ranking
    const ranking = criteria
        .map((name, idx) => ({ name, weight: weights[idx] }))
        .sort((a, b) => b.weight - a.weight);
    
    // Get top 3 for narrative (or all if fewer than 3)
    const c1 = ranking[0];
    const c2 = ranking[1];
    const c3 = ranking[ranking.length - 1];
    
    const timestamp = new Date().toLocaleDateString();
    
    // Section 1: Priority Ranking
    const priorityNarrative = `Across ${criteria.length} pairwise comparisons, ${c1.name} emerged as the dominant factor, carrying ${(c1.weight * 100).toFixed(1)}% of the total weight. ${c2.name} followed at ${(c2.weight * 100).toFixed(1)}%, a meaningful but secondary influence. ${c3.name} contributed least, at ${(c3.weight * 100).toFixed(1)}% — present in the decision, but not driving it. This ranking reflects the cumulative effect of all your individual comparisons, synthesized into normalized priority weights that sum to 100%.`;
    
    // Section 2: Consistency
    const consistencyNarrative = cr < THRESHOLD_GOOD 
        ? `Your comparisons are logically coherent — when ${c1.name} outweighs ${c2.name} and ${c2.name} outweighs ${c3.name}, your judgment reflected that ${c1.name} outweighs ${c3.name}. The weights produced here are reliable and reflect a stable preference structure.`
        : `Your comparisons contain contradictions. This doesn't invalidate the result, but it means the weights are directional rather than precise. If this decision carries significant consequence, consider revisiting the comparisons that feel least certain to improve logical consistency.`;
    
    // Section 3: Technical Metrics table with formulas
    const technicalMetrics = `
| Metric | Value | Formula | Interpretation |
|--------|-------|---------|-----------------|
| Lambda Max (λ_max) | ${lambdaMax.toFixed(4)} | Eigenvalue of pairwise matrix | Measures how well the matrix satisfies the consistency condition. Closer to n (${criteria.length}) indicates perfect consistency; higher values suggest logical contradictions. |
| Consistency Index (CI) | ${ci.toFixed(4)} | (λ_max - n) / (n - 1) | Normalized measure of deviation from perfect consistency. Lower values indicate more coherent judgments. A CI of 0 means perfect consistency. |
| Consistency Ratio (CR) | ${cr.toFixed(4)} | CI / RI | Compares your CI against a random matrix's CI (RI). CR < ${THRESHOLD_GOOD} is excellent; ${THRESHOLD_GOOD} ≤ CR < ${THRESHOLD_ACCEPTABLE} is acceptable; CR ≥ ${THRESHOLD_ACCEPTABLE} suggests review. |
| Criteria Count | ${criteria.length} | n | Total number of decision criteria. The matrix dimension; more criteria mean more comparisons and potential for inconsistency. |
`;

    const methodNarrative = `This analysis uses the Analytical Hierarchy Process (AHP), a mathematical framework that converts subjective pairwise judgments into objective priority weights. Your ${criteria.length} × ${criteria.length} comparison matrix was processed to extract the principal eigenvector, which represents your underlying preference structure. The consistency metrics validate whether your individual judgments form a logically coherent whole.`;

    const markdown = `# AHP Decision Analysis

**Generated:** ${timestamp} | **Criteria:** ${criteria.length} | **Consistency Ratio:** ${cr.toFixed(4)}

## What your comparisons revealed

${priorityNarrative}

| Rank | Criterion | Weight |
|------|-----------|--------|
${ranking.map((item, idx) => `| ${idx + 1} | ${item.name} | ${(item.weight * 100).toFixed(2)}% |`).join('\n')}

## How reliable are these results

Consistency Ratio: ${cr.toFixed(4)}. ${cr < THRESHOLD_GOOD ? `Below ${THRESHOLD_GOOD} threshold — excellent consistency.` : cr < THRESHOLD_ACCEPTABLE ? `Between ${THRESHOLD_GOOD} and ${THRESHOLD_ACCEPTABLE} — acceptable, with minor contradictions.` : `Above ${THRESHOLD_ACCEPTABLE} — review recommended.`}

${consistencyNarrative}

## Methodology reference

${technicalMetrics}

### How AHP works

${methodNarrative} Each pairwise comparison (e.g., "Does Cost matter more than Speed?") is captured on a 9-point scale, then synthesized mathematically to produce the priority weights above.

## A note on interpretation

AHP surfaces the internal logic of your own priorities — it does not make the decision for you. Use these weights as a structured input, not a final answer. Your judgment, context, and information beyond this analysis remain the deciding factors. If your CR exceeds the acceptable threshold, treat the results as directional guidance rather than precise rankings.

---

Generated by AHP Decision Dashboard, Noufal Rizka · ${timestamp}`;

    return markdown;
}

function downloadReport(criteria, results) {
    const markdown = generateMarkdownReport(criteria, results);
    
    // Create blob
    const blob = new Blob([markdown], { type: 'text/markdown' });
    
    // Create download link
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AHP-Report-${new Date().toISOString().split('T')[0]}.md`;
    
    // Trigger download
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
}

window.generateMarkdownReport = generateMarkdownReport;
window.downloadReport = downloadReport;
